export interface FFItem {
  id: string;
  name: string;
  category: "Bundle" | "Evo Weapon" | "Emote" | "Rare Item" | "Pet" | "Elite Pass" | "Booyah Pass" | "Collaboration" | "Incubator";
  rarity: "Common" | "Rare" | "Epic" | "Mythic" | "Legendary";
  description: string;
}

export const FF_ITEMS: FFItem[] = [
  // Passes (Full Elite Pass History S1-S55 & Booyah Pass)
  { id: "ep-s1", name: "EP S1: Sakura", category: "Elite Pass", rarity: "Legendary", description: "Season 1 (June 2018). Maximum rarity." },
  { id: "ep-s2", name: "EP S2: Hip Hop", category: "Elite Pass", rarity: "Legendary", description: "Season 2 (July 2018). Iconic second pass." },
  { id: "ep-s3", name: "EP S3: Doomsday Madness", category: "Elite Pass", rarity: "Legendary", description: "Season 3 (August 2018)." },
  { id: "ep-s4", name: "EP S4: Royal Revelry", category: "Elite Pass", rarity: "Legendary", description: "Season 4 (September 2018)." },
  { id: "ep-s5", name: "EP S5: Pirates", category: "Elite Pass", rarity: "Legendary", description: "Season 5 (October 2018)." },
  { id: "ep-s6", name: "EP S6: Arcade Mayhem", category: "Elite Pass", rarity: "Epic", description: "Season 6 (November 2018)." },
  { id: "ep-s7", name: "EP S7: Steampunk", category: "Elite Pass", rarity: "Epic", description: "Season 7 (December 2018)." },
  { id: "ep-s8", name: "EP S8: Impulsive Shock", category: "Elite Pass", rarity: "Epic", description: "Season 8 (January 2019)." },
  { id: "ep-s9", name: "EP S9: Bomb Squad", category: "Elite Pass", rarity: "Epic", description: "Season 9 (February 2019)." },
  { id: "ep-s10", name: "EP S10: Anubis Legends", category: "Elite Pass", rarity: "Epic", description: "Season 10 (March 2019)." },
  { id: "ep-s11", name: "EP S11: Dragon Slayers", category: "Elite Pass", rarity: "Epic", description: "Season 11 (April 2019)." },
  { id: "ep-s12", name: "EP S12: Jaguar", category: "Elite Pass", rarity: "Epic", description: "Season 12 (May 2019)." },
  { id: "ep-s13", name: "EP S13: Blood Demon", category: "Elite Pass", rarity: "Legendary", description: "Season 13 (June 2019)." },
  { id: "ep-s14", name: "EP S14: Primal Hunter", category: "Elite Pass", rarity: "Epic", description: "Season 14 (July 2019)." },
  { id: "ep-s15", name: "EP S15: Sandstorm Warriors", category: "Elite Pass", rarity: "Epic", description: "Season 15 (August 2019)." },
  { id: "ep-s16", name: "EP S16: Gunslinger", category: "Elite Pass", rarity: "Epic", description: "Season 16 (September 2019)." },
  { id: "ep-s17", name: "EP S17: Bloodwing", category: "Elite Pass", rarity: "Epic", description: "Season 17 (October 2019)." },
  { id: "ep-s18", name: "EP S18: Penalty Kick", category: "Elite Pass", rarity: "Epic", description: "Season 18 (November 2019)." },
  { id: "ep-s19", name: "EP S19: Ghost Pirates", category: "Elite Pass", rarity: "Legendary", description: "Season 19 (December 2019)." },
  { id: "ep-s20", name: "EP S20: Shadow Combat", category: "Elite Pass", rarity: "Epic", description: "Season 20 (January 2020)." },
  { id: "ep-s21", name: "EP S21: T.R.A.P. Revolutions", category: "Elite Pass", rarity: "Legendary", description: "Season 21 (February 2020)." },
  { id: "ep-s22", name: "EP S22: Desert Hunter", category: "Elite Pass", rarity: "Epic", description: "Season 22 (March 2020)." },
  { id: "ep-s23", name: "EP S23: Agent Paws", category: "Elite Pass", rarity: "Epic", description: "Season 23 (April 2020)." },
  { id: "ep-s24", name: "EP S24: Forsaken Creed", category: "Elite Pass", rarity: "Epic", description: "Season 24 (May 2020)." },
  { id: "ep-s25", name: "EP S25: Fabled Fox", category: "Elite Pass", rarity: "Epic", description: "Season 25 (June 2020)." },
  { id: "ep-s26", name: "EP S26: Rampage II: Uprising", category: "Elite Pass", rarity: "Epic", description: "Season 26 (July 2020)." },
  { id: "ep-s27", name: "EP S27: Sushi Menace", category: "Elite Pass", rarity: "Epic", description: "Season 27 (August 2020)." },
  { id: "ep-s28", name: "EP S28: Celestial Street", category: "Elite Pass", rarity: "Epic", description: "Season 28 (September 2020)." },
  { id: "ep-s29", name: "EP S29: Anubis Legend II", category: "Elite Pass", rarity: "Epic", description: "Season 29 (October 2020)." },
  { id: "ep-s30", name: "EP S30: Ultrasonic Rave", category: "Elite Pass", rarity: "Epic", description: "Season 30 (November 2020)." },
  { id: "ep-s31", name: "EP S31: Endless Oblivion", category: "Elite Pass", rarity: "Epic", description: "Season 31 (December 2020)." },
  { id: "ep-s32", name: "EP S32: Specter Squad", category: "Elite Pass", rarity: "Epic", description: "Season 32 (January 2021)." },
  { id: "ep-s33", name: "EP S33: Fuji Folklore", category: "Elite Pass", rarity: "Epic", description: "Season 33 (February 2021)." },
  { id: "ep-s34", name: "EP S34: Willful Wonders", category: "Elite Pass", rarity: "Epic", description: "Season 34 (March 2021)." },
  { id: "ep-s35", name: "EP S35: Bloodwing City", category: "Elite Pass", rarity: "Epic", description: "Season 35 (April 2021)." },
  { id: "ep-s36", name: "EP S36: Theatre of Torment", category: "Elite Pass", rarity: "Epic", description: "Season 36 (May 2021)." },
  { id: "ep-s37", name: "EP S37: Evil Enchanted", category: "Elite Pass", rarity: "Epic", description: "Season 37 (June 2021)." },
  { id: "ep-s38", name: "EP S38: Guns for Hire", category: "Elite Pass", rarity: "Epic", description: "Season 38 (July 2021)." },
  { id: "ep-s39", name: "EP S39: Wildland Walkers", category: "Elite Pass", rarity: "Epic", description: "Season 39 (August 2021)." },
  { id: "ep-s40", name: "EP S40: Quilled Quiver", category: "Elite Pass", rarity: "Epic", description: "Season 40 (September 2021)." },
  { id: "ep-s41", name: "EP S41: Mesmerizing Nights", category: "Elite Pass", rarity: "Epic", description: "Season 41 (October 2021)." },
  { id: "ep-s42", name: "EP S42: Inferno Rage", category: "Elite Pass", rarity: "Epic", description: "Season 42 (November 2021)." },
  { id: "ep-s43", name: "EP S43: Palace of Poker", category: "Elite Pass", rarity: "Epic", description: "Season 43 (December 2021)." },
  { id: "ep-s44", name: "EP S44: Planet Rogue", category: "Elite Pass", rarity: "Epic", description: "Season 44 (January 2022)." },
  { id: "ep-s45", name: "EP S45: Papyrus Rebel", category: "Elite Pass", rarity: "Epic", description: "Season 45 (February 2022)." },
  { id: "ep-s46", name: "EP S46: Copper Glaze", category: "Elite Pass", rarity: "Epic", description: "Season 46 (March 2022)." },
  { id: "ep-s47", name: "EP S47: Scrolls of Azure", category: "Elite Pass", rarity: "Epic", description: "Season 47 (April 2022)." },
  { id: "ep-s48", name: "EP S48: Checkmate Knight", category: "Elite Pass", rarity: "Epic", description: "Season 48 (May 2022)." },
  { id: "ep-s49", name: "EP S49: Cyber Blade", category: "Elite Pass", rarity: "Epic", description: "Season 49 (June 2022)." },
  { id: "ep-s50", name: "EP S50: Bumble Rumblers", category: "Elite Pass", rarity: "Epic", description: "Season 50 (July 2022)." },
  { id: "ep-s51", name: "EP S51: Kung-foodies", category: "Elite Pass", rarity: "Epic", description: "Season 51 (August 2022)." },
  { id: "ep-s52", name: "EP S52: Deep Sea Warriors", category: "Elite Pass", rarity: "Epic", description: "Season 52 (September 2022)." },
  { id: "ep-s53", name: "EP S53: Jutsu Elemental", category: "Elite Pass", rarity: "Epic", description: "Season 53 (October 2022)." },
  { id: "ep-s54", name: "EP S54: Electrical Velocity", category: "Elite Pass", rarity: "Epic", description: "Season 54 (November 2022)." },
  { id: "ep-s55", name: "EP S55: Avalanche", category: "Elite Pass", rarity: "Epic", description: "Season 55 (December 2022). Final Elite Pass." },
  { id: "bp-all", name: "B.P: Todos los Booyah Pass", category: "Booyah Pass", rarity: "Epic", description: "Colección completa de Booyah Passes." },
  { id: "ep-all", name: "E.P: Todos los Elite Pass", category: "Elite Pass", rarity: "Legendary", description: "Colección completa de todos los Elite Pass (S1-S55)." },
  
  // Evo Weapons (Comprehensive List)
  { id: "ak-dragon", name: "AK-47 Blue Flame Draco (Max)", category: "Evo Weapon", rarity: "Legendary", description: "First Evolutive weapon skin." },
  { id: "mp40-cobra", name: "MP40 Predatory Cobra (Max)", category: "Evo Weapon", rarity: "Legendary", description: "The iconic Cobra Evolutive weapon." },
  { id: "m1014-dragon", name: "M1014 Green Flame Draco (Max)", category: "Evo Weapon", rarity: "Legendary", description: "Evolutive shotgun skin." },
  { id: "scar-titan", name: "SCAR Megalodon Alpha (Max)", category: "Evo Weapon", rarity: "Legendary", description: "Powerful Evolutive SCAR." },
  { id: "ump-booyah", name: "UMP Booyah Day (Max)", category: "Evo Weapon", rarity: "Legendary", description: "Limited edition Evo UMP." },
  { id: "famas-demonic", name: "FAMAS Demonic Grin (Max)", category: "Evo Weapon", rarity: "Legendary", description: "Evil themed Evo FAMAS." },
  { id: "m4a1-inferno", name: "M4A1 Infernal Draco (Max)", category: "Evo Weapon", rarity: "Legendary", description: "Fiery Evo M4A1." },
  { id: "mp5-platinum", name: "MP5 Platinum Divinity (Max)", category: "Evo Weapon", rarity: "Legendary", description: "Holy themed Evo MP5." },
  { id: "woodpecker-majestic", name: "Woodpecker Majestic Prowess (Max)", category: "Evo Weapon", rarity: "Legendary", description: "Legendary Woodpecker." },
  { id: "m1887-sterling", name: "M1887 Sterling Conqueror (Max)", category: "Evo Weapon", rarity: "Legendary", description: "Impactful Evo M1887." },
  { id: "xm8-destiny", name: "XM8 Destiny Guardian (Max)", category: "Evo Weapon", rarity: "Legendary", description: "Lightning themed Evo XM8." },
  { id: "an94-evil", name: "AN94 Evil Howler (Max)", category: "Evo Weapon", rarity: "Legendary", description: "Wolf themed Evo AN94." },
  { id: "thompson-cindered", name: "Thompson Cindered Colossus (Max)", category: "Evo Weapon", rarity: "Legendary", description: "Latest Evo Thompson." },
  { id: "m1014-scorpio", name: "M1014 Scorpio Shatter (Max)", category: "Evo Weapon", rarity: "Legendary", description: "Second Evo M1014." },
  { id: "evo-all", name: "Todas las Armas Evolutivas (Max)", category: "Evo Weapon", rarity: "Legendary", description: "Colección completa de armas evolutivas al nivel máximo." },

  // Collaborations (Chronological 2019-2025)
  { id: "collab-alok", name: "Collab: DJ Alok (2019)", category: "Collaboration", rarity: "Epic", description: "First major real-life collaboration (Nov 2019). Iconic character and 'Vale Vale' emote." },
  { id: "collab-ragnarok", name: "Collab: Ragnarok (2020)", category: "Collaboration", rarity: "Epic", description: "First major anime collab (March 2020). Assassin Cross and Poring pet." },
  { id: "collab-lcdp", name: "Collab: Money Heist (2020)", category: "Collaboration", rarity: "Legendary", description: "La Casa de Papel heist master bundles (Sept 2020)." },
  { id: "collab-k", name: "Collab: KSHMR (2020)", category: "Collaboration", rarity: "Epic", description: "Collab with DJ KSHMR (Oct 2020). Character K and 'One More Round' theme." },
  { id: "collab-cr7", name: "Collab: CR7 Chrono (2020)", category: "Collaboration", rarity: "Legendary", description: "Operation Chrono with Cristiano Ronaldo (Dec 2020)." },
  { id: "collab-opm", name: "Collab: One Punch Man (2021)", category: "Collaboration", rarity: "Legendary", description: "Saitama and Genos bundles (Jan 2021)." },
  { id: "collab-skyler", name: "Collab: Skyler (2021)", category: "Collaboration", rarity: "Epic", description: "Collab with Son Tung M-TP (Feb 2021). Character Skyler." },
  { id: "collab-aot", name: "Collab: Attack on Titan (2021)", category: "Collaboration", rarity: "Legendary", description: "Levi & Mikasa bundles and M1014 Colossal Titan (March 2021)." },
  { id: "collab-mclaren", name: "Collab: McLaren P1™ (2021)", category: "Collaboration", rarity: "Legendary", description: "McLaren Racing supercar series (July 2021)." },
  { id: "collab-sf", name: "Collab: Street Fighter V (2021)", category: "Collaboration", rarity: "Legendary", description: "Ryu and Chun-Li bundles (July 2021)." },
  { id: "collab-venom", name: "Collab: Venom (2021)", category: "Collaboration", rarity: "Epic", description: "Venom: Let There Be Carnage official collab (Oct 2021)." },
  { id: "collab-jbalvin", name: "Collab: J Balvin (2022)", category: "Collaboration", rarity: "Epic", description: "Everything Goes bundle and thematic skins (Jan 2022)." },
  { id: "collab-jjk", name: "Collab: Jujutsu Kaisen (2022)", category: "Collaboration", rarity: "Legendary", description: "Yuji Itadori and Satoru Gojo sets (March 2022)." },
  { id: "collab-ac", name: "Collab: Assassin's Creed (2022)", category: "Collaboration", rarity: "Epic", description: "Ezio Auditore bundle and Leap of Faith emote (March 2022)." },
  { id: "collab-bts", name: "Collab: BTS (2022)", category: "Collaboration", rarity: "Legendary", description: "Set of 7 BTS-designed bundles (March 2022)." },
  { id: "collab-anitta", name: "Collab: Anitta (2022)", category: "Collaboration", rarity: "Epic", description: "A Patroa character and bundle (July 2022)." },
  { id: "collab-jb", name: "Collab: Justin Bieber (2022)", category: "Collaboration", rarity: "Epic", description: "Indulgent Indulgence set (August 2022)." },
  { id: "collab-dmc", name: "Collab: Devil May Cry 5 (2023)", category: "Collaboration", rarity: "Legendary", description: "Dante and Nero bundles (Feb 2023)." },
  { id: "collab-spiderman", name: "Collab: Spider-Man (2023)", category: "Collaboration", rarity: "Epic", description: "Across the Spider-Verse suit (June 2023)." },
  { id: "collab-ds", name: "Collab: Demon Slayer (2023)", category: "Collaboration", rarity: "Legendary", description: "Tanjiro and Nezuko bundles (Sept 2023)." },
  { id: "collab-lambo", name: "Collab: Lamborghini (2023)", category: "Collaboration", rarity: "Legendary", description: "High-performance car skins (Dec 2023)." },
  { id: "collab-bluelock", name: "Collab: Blue Lock (2024)", category: "Collaboration", rarity: "Legendary", description: "Isagi and Bachira sets (July 2024)." },
  { id: "collab-gintama", name: "Collab: Gintama (2024)", category: "Collaboration", rarity: "Legendary", description: "Gintoki Sakata and Kagura bundles (Oct 2024)." },
  { id: "collab-naruto", name: "Collab: Naruto Shippuden (2025)", category: "Collaboration", rarity: "Legendary", description: "Naruto and Sasuke bundles (Planned Jan 2025)." },
  { id: "collab-all", name: "Todas las Colaboraciones", category: "Collaboration", rarity: "Legendary", description: "Colección masiva de todas las colaboraciones históricas oficializadas." },

  // Incubators (Notable & Chronological)
  { id: "inc-dino", name: "Inc: Dino (Dec 2018)", category: "Incubator", rarity: "Legendary", description: "The very first incubator. Featuring the iconic Dino suits." },
  { id: "inc-criminal", name: "Inc: Top Criminal (Jan 2019)", category: "Incubator", rarity: "Mythic", description: "Color-themed criminal suits. Highly rare and legendary." },
  { id: "inc-sunmoon", name: "Inc: Luna y Sol (Feb 2019)", category: "Incubator", rarity: "Epic", description: "Ancient Sun and Moon themed bundles." },
  { id: "inc-ak-unicorn", name: "Inc: AK-47 Unicorn (April 2019)", category: "Incubator", rarity: "Legendary", description: "Golden, Ice, and Fire unicorn themed AK skins." },
  { id: "inc-scar-beast", name: "Inc: Scar Bestia (May 2019)", category: "Incubator", rarity: "Legendary", description: "Potent Scar weapon skins with unique attributes." },
  { id: "inc-yinyang", name: "Inc: Maestros Místicos (Sept 2019)", category: "Incubator", rarity: "Epic", description: "Yin Yang themed traditional bundles." },
  { id: "inc-samurai", name: "Inc: Samurai Dorado (Dec 2019)", category: "Incubator", rarity: "Legendary", description: "Golden and Silver samurai traditional armors." },
  { id: "inc-graffiti", name: "Inc: Graffiti Squad (Jan 2020)", category: "Incubator", rarity: "Epic", description: "Urban street art themed bundles." },
  { id: "inc-poker", name: "Inc: MP40 Poker (March 2020)", category: "Incubator", rarity: "Legendary", description: "Flashing Spade and Eternal Diamond MP40 skins." },
  { id: "inc-apocalyptic", name: "Inc: Apocalipsis M1014 (July 2020)", category: "Incubator", rarity: "Legendary", description: "Four versions of the powerful M1014 shotgun." },
  { id: "inc-spiritual", name: "Inc: Fuerza Espiritual (Nov 2020)", category: "Incubator", rarity: "Epic", description: "Spiritual and mystical warrior bundles." },
  { id: "inc-timetraveller", name: "Inc: Viajeros del Tiempo (Dec 2020)", category: "Incubator", rarity: "Epic", description: "Thompson skins and thematic bundles." },
  { id: "inc-netherworld", name: "Inc: Inframundo (Feb 2021)", category: "Incubator", rarity: "Epic", description: "M4A1 skins and demonic themed bundles." },
  { id: "inc-mythos", name: "Inc: Mythos Modernos (July 2021)", category: "Incubator", rarity: "Epic", description: "Ancient mythology meets modern tech." },
  { id: "inc-geometric", name: "Inc: Geometric Shock (Sept 2021)", category: "Incubator", rarity: "Epic", description: "Abstract geometric design bundles." },
  { id: "inc-all", name: "Todas las Incubadoras", category: "Incubator", rarity: "Legendary", description: "Logro de coleccionista por obtener todas las incubadoras históricas." },

  // Bundles (General)
  { id: "sakura", name: "Sakura Bundle", category: "Bundle", rarity: "Legendary", description: "Season 1 Elite Pass bundle." },
  { id: "hip-hop", name: "Hip Hop Bundle", category: "Bundle", rarity: "Legendary", description: "Season 2 Elite Pass bundle." },
  { id: "criminal-red", name: "Red Criminal Bundle", category: "Bundle", rarity: "Mythic", description: "Rare incubator bundle." },
  { id: "criminal-green", name: "Green Criminal Bundle", category: "Bundle", rarity: "Epic", description: "Very rare giveaway bundle." },
  { id: "criminal-yellow", name: "Yellow Criminal Bundle", category: "Bundle", rarity: "Mythic", description: "Rare incubator bundle." },
  { id: "criminal-blue", name: "Blue Criminal Bundle", category: "Bundle", rarity: "Mythic", description: "Rare incubator bundle." },
  { id: "criminal-purple", name: "Purple Criminal Bundle", category: "Bundle", rarity: "Mythic", description: "Rare incubator bundle." },
  { id: "arctic-blue", name: "Arctic Blue Bundle", category: "Bundle", rarity: "Mythic", description: "Magic Cube bundle." },
  { id: "bundle-dino", name: "Pink Dino Bundle", category: "Bundle", rarity: "Epic", description: "Rare Incubator Dino series." },
  { id: "skull-hunter", name: "Skull Hunter Bundle", category: "Bundle", rarity: "Legendary", description: "First Legendary level-up bundle." },

  // Items
  { id: "angelic-pants", name: "Angelic Pants (Male)", category: "Rare Item", rarity: "Legendary", description: "Extremely sought-after clothing." },
  { id: "alok", name: "DJ Alok", category: "Rare Item", rarity: "Epic", description: "Top character." },
  { id: "emote-f-throne", name: "FFWC Throne Emote", category: "Emote", rarity: "Epic", description: "Rare throne emote." },
  { id: "magic-cube", name: "Magic Cube", category: "Rare Item", rarity: "Mythic", description: "Exchangeable for rare bundles." },
];

export const REGIONS = [
  "Global",
  "Latam (Sudamérica/Norte)",
  "Brazil",
  "India",
  "Thailand",
  "Europe",
  "Indonesia"
];

export const RANKS = [
  "Bronze",
  "Silver",
  "Gold",
  "Platinum",
  "Diamond",
  "Heroic",
  "Master",
  "Grandmaster"
];
